### PR TITLE
fix search and ip geocode params

### PR DESCRIPTION
**Pull request by brettguenther**
@nickpatrick - some simple fixes here in the example project

### CODE REVIEW

**Comment by nickpatrick** [comment]
Thanks.`withRadius` should be `radius`. Will fix in another PR.

**Comment by nickpatrick** [comment]
@pingxia0823 This was a side effect of `clang-format` breaking `NS_SWIFT_NAME` macros into two lines. I'll see if I can figure out how to stop this from happening.

**Comment by nickpatrick** [comment]
@pingxia0823 For now I just switched `ColumnLimit: 160` to `ColumnLimit: 180`. Will merge #67 later today.

**Comment by pingxia0823** [comment]
kk, I'll check the clang doc

**Comment by pingxia0823** [comment]
We probably need to add some sanity checks for the swift example code

**Comment by nickpatrick** [comment]
@pingxia0823 Good call, I just added sample app build to CI:
https://github.com/radarlabs/radar-sdk-ios/pull/67/files#diff-1d37e48f9ceff6d8030570cd36286a61R31
https://github.com/radarlabs/radar-sdk-ios/pull/67/files#diff-b67911656ef5d18c4ae36cb6741b7965R43

**Pull request closed without merging**
