### PR TITLE
support splitting "name" into "addressLabel" and "placeLabel"

### PR DESCRIPTION
**Pull request by kochis**

### CODE REVIEW

**Comment by pingxia0823** [comment]
just saw the linked server change. got it

**Comment by jsani-radar** [comment]
@pingxia0823 -- it's so we can better segment the results we return for projects that have places enabled / disabled, we don't want to be returning place records for `project.settings.places = false`

**Comment by kochis** [comment]
I ran `make test-pretty` and it looks like that builds the binaries. Should those not be checked in?

**Comment by pingxia0823** [comment]
the `/dist/` is a bit annoying. It really shall be git ignored, just like the `server` repo

**Comment by jsani-radar** [comment]
Didn't realize `make test-pretty` did that 😕- although we can't completely ignore `dist/` because we need to do so when we actually release, this is a topic of convo that's come up before, would like to streamline the SDK release process as a result

**Pull request merged**
